version: '3.8'

services:

  backend:
    build:
      context: ./back-end
      target: development
    volumes:
      - ./back-end/src:/back-end/src
    ports:
      - 8082:8082

  client_root:
    build:
      context: ./front-end-root
      target: development
    volumes:
      - ./front-end-root/src:/front-end-root/src
    ports:
      - 9000:9000

  client_navigation:
    build:
      context: ./front-end-navigation
      target: development
    volumes:
      - ./front-end-navigation/src:/front-end-navigation/src
    ports:
      - 9010:9010

  client_topbar:
    build:
      context: ./front-end-topbar
      target: development
    volumes:
      - ./front-end-topbar/src:/front-end-topbar/src
    ports:
      - 9020:9020

  client_utils:
    build:
      context: ./front-end-utils
      target: development
    volumes:
      - ./front-end-utils/src:/front-end-utils/src
    ports:
      - 9030:9030

  nginx:
    image: nginx
    depends_on:
      - backend
      - client_root
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"